<?php
require_once(dirname(__FILE__).'/activate-upgrade.php');
require_once(dirname(__FILE__).'/status.php');
require_once(dirname(__FILE__).'/countries.php');
require_once(dirname(__FILE__).'/menu.php');
require_once(dirname(__FILE__).'/styles.php');
require_once(dirname(__FILE__).'/admin-page.php');
require_once(dirname(__FILE__).'/controls.php');
require_once(dirname(__FILE__).'/jquery.php');
?>