editAreaLoader.lang["id"]={
new_document: "dokumen baru",
search_button: "cari dan ganti",
search_command: "cari lagi / buka area pencarian",
search: "cari",
replace: "ganti",
replace_command: "ganti / buka area pencarian",
find_next: "cari lagi",
replace_all: "ganti semua",
reg_exp: "regular expressions",
match_case: "kapitalisasi",
not_found: "tidak ditemukan.",
occurrence_replaced: "occurences replaced.",
search_field_empty: "Kata kunci kosong",
restart_search_at_begin: "Area habis. Mulai lagi dari awal.",
move_popup: "geser popup pencarian",
font_size: "--Ukuran huruf--",
go_to_line: "menuju baris",
go_to_line_prompt: "menuju baris ke:",
undo: "undo",
redo: "redo",
change_smooth_selection: "hidupkan/matikan beberapa fitur tampilan (tampilan lebih baik, sumberdaya CPU lebih besar)",
highlight: "penanda syntax matikan/hidupkan",
reset_highlight: "reset highlight (jika tidak sinkron dengan text)",
word_wrap: "potong baris panjang",
help: "tentang",
save: "simpan",
load: "ambil",
line_abbr: "Baris",
char_abbr: "Kolom",
position: "Posisi",
total: "Total",
close_popup: "tutup popup",
shortcuts: "Pintasan",
add_tab: "tambah tab ke text",
remove_tab: "hapus tab dari text",
about_notice: "Catatan: fungsi syntax highlight hanya untuk text kecil",
toggle: "Matikan/hidupkan editor",
accesskey: "Kunci akses",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Memproses...",
fullscreen: "layarpenuh",
syntax_selection: "--Bahasa--",
close_tab: "Tutup file"
};
